<a href="https://colab.research.google.com/github/OlhaMir/testolha/blob/norma/%D0%9B%D0%B5%D0%BA%D1%86%D1%96%D1%8F2%D0%9C%D1%96%D1%80%D0%BE%D1%88%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy: масиви, векторизація та лінійна алгебра для машинного навчання

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)

m = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.int64)

print("Вектор a:")
print(a)

print("\nМатриця M:")
print(m)

Вектор a:
[1. 2. 3. 4. 5.]

Матриця M:
[[1 2 3]
 [4 5 6]]


In [ ]:
print("shape:", m.shape)
print("ndim:", m.ndim)
print("size:", m.size)
print("dtype:", m.dtype)
print("itemsize:", m.itemsize)
print("nbytes:", m.nbytes)

shape: (2, 3)
ndim: 2
size: 6
dtype: int64
itemsize: 8
nbytes: 48


In [ ]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Матриця:")
print(matrix)

print("shape:", matrix.shape)
print("ndim:", matrix.ndim)
print("size:", matrix.size)
print("dtype:", matrix.dtype)
print("nbytes:", matrix.nbytes)

Матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4)
ndim: 2
size: 12
dtype: int64
nbytes: 96


In [ ]:
a = np.array([1, 2, 3, 4])
zeros = np.zeros((2, 3), dtype=np.float32)
ones = np.ones((2, 3), dtype=np.int64)
full = np.full((2, 3), 7)
i = np.eye(4)

print("a =", a)
print("\nzeros =\n", zeros)
print("\nones =\n", ones)
print("\nfull =\n", full)
print("\nI =\n", i)

a = [1 2 3 4]

zeros =
 [[0. 0. 0.]
 [0. 0. 0.]]

ones =
 [[1 1 1]
 [1 1 1]]

full =
 [[7 7 7]
 [7 7 7]]

I =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
x1 = np.arange(0, 1, 0.2)
x2 = np.linspace(0, 1, num=6)

print("arange:", x1)
print("linspace:", x2)

arange: [0.  0.2 0.4 0.6 0.8]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
x = np.array([1, 2, 3], dtype=np.int32)
y = x.astype(np.float32)

print("x.dtype:", x.dtype)
print("y.dtype:", y.dtype)

x.dtype: int32
y.dtype: float32


In [ ]:
a = np.array([1, 2, 3], dtype=np.float32)
b = np.float64(0.5)
c = a + b

print(c)
print("dtype результату:", c.dtype)

[1.5 2.5 3.5]
dtype результату: float64


In [ ]:
arr64 = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float64)

arr32 = arr64.astype(np.float32)

print("Масив float64:", arr64)
print("dtype:", arr64.dtype)
print("itemsize:", arr64.itemsize)
print("nbytes:", arr64.nbytes)

print("\nМасив float32:", arr32)
print("dtype:", arr32.dtype)
print("itemsize:", arr32.itemsize)
print("nbytes:", arr32.nbytes)

Масив float64: [1.1 2.2 3.3 4.4 5.5]
dtype: float64
itemsize: 8
nbytes: 40

Масив float32: [1.1 2.2 3.3 4.4 5.5]
dtype: float32
itemsize: 4
nbytes: 20


In [ ]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[-1])
print(a[1:4])
print(a[::2])

m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\nM[1, 1] =", m[1, 1])
print("M[1:, 1] =", m[1:, 1])
print("M[0, :2] =", m[0, :2])

10
50
[20 30 40]
[10 30 50]

M[1, 1] = 5
M[1:, 1] = [5 8]
M[0, :2] = [1 2]


In [ ]:
scores = np.array([56, 82, 91, 47, 73])
mask = scores >= 60

print("mask:", mask)
print("scores[mask]:", scores[mask])

passed = scores[scores >= 60]
print("passed:", passed)

mask: [False  True  True False  True]
scores[mask]: [82 91 73]
passed: [82 91 73]


In [ ]:
a = np.array([10, 20, 30, 40, 50])
idx = np.array([4, 0, 2])

print(a[idx])

[50 10 30]


In [ ]:
scores = np.array([55, 72, 88, 65, 91, 70, 84, 95, 79, 60])

result = scores[(scores >= 70) & (scores <= 90)]

print(result)

[72 88 70 84 79]


In [ ]:
a = np.array([1, 2, 3, 4, 5])

view = a[1:4]
view[0] = 99

print("Після зміни view:")
print("a =", a)
print("view =", view)

a = np.array([1, 2, 3, 4, 5])

copy = a[1:4].copy()
copy[0] = 99

print("\nПісля зміни copy:")
print("a =", a)
print("copy =", copy)

Після зміни view:
a = [ 1 99  3  4  5]
view = [99  3  4]

Після зміни copy:
a = [1 2 3 4 5]
copy = [99  3  4]


In [ ]:
values = [1, 2, 3, 4]

# Python
squared_loop = [x ** 2 for x in values]

# NumPy
a = np.array(values)
squared_numpy = a ** 2

print("Python:", squared_loop)
print("NumPy:", squared_numpy)

Python: [1, 4, 9, 16]
NumPy: [ 1  4  9 16]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)
print("a * b =", a * b)
print("a @ b =", a @ b)

a + b = [5 7 9]
a * b = [ 4 10 18]
a @ b = 32


In [ ]:
x = np.array([1.0, 4.0, 9.0])

print("sqrt:", np.sqrt(x))
print("log:", np.log(x))
print("maximum:", np.maximum(x, 5.0))

sqrt: [1. 2. 3.]
log: [0.         1.38629436 2.19722458]
maximum: [5. 5. 9.]


In [ ]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

bias = np.array([10, 20, 30])

print("X.shape:", x.shape)
print("bias.shape:", bias.shape)
print("\nX + bias =\n", x + bias)

X.shape: (2, 3)
bias.shape: (3,)

X + bias =
 [[11 22 33]
 [14 25 36]]


In [ ]:
x = np.array([
    [170., 65.],
    [180., 80.],
    [160., 55.]
])

mean =x.mean(axis=0)
std = x.std(axis=0)
x_scaled = (x - mean) / std

print("mean:", mean)
print("std:", std)
print("\nX_scaled =\n", x_scaled)

mean: [170.          66.66666667]
std: [ 8.16496581 10.27402334]

X_scaled =
 [[ 0.         -0.16222142]
 [ 1.22474487  1.29777137]
 [-1.22474487 -1.13554995]]


In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

numbers = np.array([10, 20, 30])

result = matrix + numbers

print("Початкова матриця:")
print(matrix)

print("\nРезультат:")
print(result)

Початкова матриця:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Результат:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("sum:", m.sum())
print("sum(axis=0):", m.sum(axis=0))
print("sum(axis=1):", m.sum(axis=1))
print("mean(axis=0):", m.mean(axis=0))

sum: 21
sum(axis=0): [5 7 9]
sum(axis=1): [ 6 15]
mean(axis=0): [2.5 3.5 4.5]


In [ ]:
x = np.array([10.0, np.nan, 30.0, 40.0])

print("np.mean(x):", np.mean(x))
print("np.nanmean(x):", np.nanmean(x))

np.mean(x): nan
np.nanmean(x): 26.666666666666668


In [ ]:
a = np.arange(12)
m = a.reshape(3, 4)

print("M =\n", m)
print("\nM.T =\n", m.T)
print("\nravel:", m.ravel())
print("flatten:", m.flatten())

M =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

M.T =
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
x = np.array([1, 2, 3])

row = x[np.newaxis, :]
col = x[:, np.newaxis]

print("x.shape:", x.shape)
print("row.shape:", row.shape)
print("col.shape:", col.shape)


print("\nx =\n", x)
print("\nrow =\n", row)
print("\ncol =\n", col)

x.shape: (3,)
row.shape: (1, 3)
col.shape: (3, 1)

x =
 [1 2 3]

row =
 [[1 2 3]]

col =
 [[1]
 [2]
 [3]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("a\n", a)

print("b\n", b)

print("concatenate axis=0:\n", np.concatenate([a, b], axis=0))
print("\nconcatenate axis=1:\n", np.concatenate([a, b], axis=1))
print("\nvstack:\n", np.vstack([a, b]))
print("\nhstack:\n", np.hstack([a, b]))

a
 [[1 2]
 [3 4]]
b
 [[5 6]
 [7 8]]
concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

s = np.stack([x, y], axis=0)

print(s)
print("shape:", s.shape)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)


In [ ]:
rng = np.random.default_rng(seed=42)

uniform = rng.random(5)
normal = rng.normal(loc=0.0, scale=1.0, size=5)
integers = rng.integers(0, 10, size=5)

print("uniform:", uniform)
print("normal:", normal)
print("integers:", integers)

uniform: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
normal: [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
integers: [5 3 1 9 7]


In [ ]:
rng = np.random.default_rng(123)

idx = np.arange(10)
rng.shuffle(idx)

sample = rng.choice(np.arange(100), size=5, replace=False)

print("shuffled idx:", idx)
print("sample:", sample)

shuffled idx: [7 4 0 2 1 5 6 8 3 9]
sample: [77 43 90 27 44]


In [ ]:
matrix = np.random.normal(size=(4, 3))

numbers = np.random.randint(1, 101, size=10)

indices = np.random.choice(20, size=5, replace=False)

print("Матриця (4, 3):")
print(matrix)

print("\n10 випадкових цілих чисел:")
print(numbers)

print("\n5 різних індексів:")
print(indices)

Матриця (4, 3):
[[ 1.33928375  0.00788908  1.26943063]
 [ 0.15537707  0.01837755  0.19735941]
 [-0.46220285 -0.21628292  0.53872614]
 [ 0.15402806  0.28135197 -0.31801862]]

10 випадкових цілих чисел:
[ 99  65  70   9  85  66 100  85  17  80]

5 різних індексів:
[16  5 10 17 12]


In [ ]:
a = np.array([
    [1, 2, 3],
    [0, 1, 2]
])

b = np.array([
    [ 1, 2],
    [ 0, 4],
    [-1, 0]
])

c = a @ b
print(c)

[[-2 10]
 [-2  4]]


In [ ]:
a = np.array([
    [ 1.,  0., 3.],
    [-1., -1., 2.],
    [ 4.,  7., 2.]
])

print("diag:", np.diag(a))
print("\nA.T =\n", a.T)

det = np.linalg.det(a)
print("\ndet(A) =", det)
print("det близький до -25:", np.isclose(det, -25.0))

diag: [ 1. -1.  2.]

A.T =
 [[ 1. -1.  4.]
 [ 0. -1.  7.]
 [ 3.  2.  2.]]

det(A) = -24.999999999999996
det близький до -25: True


In [ ]:
a = np.array([
    [1.,  2.,  5.],
    [1., -1.,  3.],
    [3., -6., -1.]
])

b = np.array([-9., 2., 25.])

x = np.linalg.solve(a, b)

print("x =", x)
print("Перевірка A @ x ≈ b:", np.allclose(a @ x, b))

x = [ 2. -3. -1.]
Перевірка A @ x ≈ b: True


In [ ]:
x = np.array([
    [1., 1.],
    [1., 2.],
    [1., 3.],
    [1., 4.]
])

y = np.array([2.1, 3.9, 6.2, 8.1])

beta, residuals, rank, s = np.linalg.lstsq(x, y, rcond=None)

print("beta:", beta)
print("residuals:", residuals)
print("rank:", rank)
print("singular values:", s)

beta: [6.9423189e-16 2.0300000e+00]
residuals: [0.043]
rank: 2
singular values: [5.77937881 0.77380911]


In [ ]:
a = np.array([
    [2., 1.],
    [1., 2.]
])

values, vectors = np.linalg.eigh(a)

print("Власні значення:", values)
print("Власні вектори:\n", vectors)

Власні значення: [1. 3.]
Власні вектори:
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
a = np.array([
    [3., 1.],
    [1., 3.],
    [1., 1.]
])

U, s, Vt = np.linalg.svd(a, full_matrices=False)

print("U =\n", U)
print("\ns =", s)
print("\nVt =\n", Vt)

U =
 [[-6.66666667e-01  7.07106781e-01]
 [-6.66666667e-01 -7.07106781e-01]
 [-3.33333333e-01  5.92577380e-18]]

s = [4.24264069 2.        ]

Vt =
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [ ]:
x = np.array([
    [170., 65., 25.],
    [180., 80., 31.],
    [160., 55., 22.],
    [175., 72., 28.]
])

mu = x.mean(axis=0)
sigma = x.std(axis=0)
x_std = (x - mu) / sigma

print("Середні після стандартизації:")
print(x_std.mean(axis=0))

print("\nСтандартні відхилення:")
print(x_std.std(axis=0))

Середні після стандартизації:
[0.00000000e+00 0.00000000e+00 1.38777878e-17]

Стандартні відхилення:
[1. 1. 1.]


In [ ]:
x = np.array([
    [1.0, 2.0],
    [2.0, 1.0],
    [3.0, 4.0]
])

w = np.array([0.5, -0.25])
b = 1.0

y_pred = x @ w + b

print(y_pred)

[1.   1.75 1.5 ]


In [ ]:
y_true = np.array([1.2, 1.8, 2.5])
y_pred = np.array([1.0, 2.0, 2.3])

mse = np.mean((y_true - y_pred) ** 2)

print("MSE =", mse)

MSE = 0.04000000000000001


In [ ]:
x = np.array([
    [1., 2.],
    [4., 6.],
    [2., 3.]
])

q = np.array([1., 1.])

distances = np.linalg.norm(x - q, axis=1)

print(distances)

[1.         5.83095189 2.23606798]


In [ ]:
x = np.array([7, 2, 9, 2, 5])

print("sort:", np.sort(x))
print("argsort:", np.argsort(x))
print("unique:", np.unique(x))
print("where x >= 5:", np.where(x >= 5))
print("clip 3..7:", np.clip(x, 3, 7))

sort: [2 2 5 7 9]
argsort: [1 3 4 0 2]
unique: [2 5 7 9]
where x >= 5: (array([0, 2, 4]),)
clip 3..7: [7 3 7 3 5]


In [ ]:
x = np.arange(12).reshape(3, 4)

np.save("X.npy", x)
x_loaded = np.load("X.npy")

print("X_loaded.shape:", x_loaded.shape)
print(x_loaded)

np.savez_compressed(
    "dataset.npz",
    X=x,
    y=np.array([0, 1, 1])
)

data = np.load("dataset.npz")
print("\ndata['X'] =\n", data["X"])
print("data['y'] =", data["y"])

X_loaded.shape: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

data['X'] =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
data['y'] = [0 1 1]


In [ ]:
x = np.array([1.0, np.nan, np.inf, -5.0])

print("isfinite:", np.isfinite(x))
print("Скінченні значення:", x[np.isfinite(x)])

isfinite: [ True False False  True]
Скінченні значення: [ 1. -5.]


In [ ]:
a = 0.1 + 0.2
b = 0.3
print("a ", a)

print("a == b:", a == b)
print("np.isclose(a, b):", np.isclose(a, b))

a  0.30000000000000004
a == b: False
np.isclose(a, b): True


In [ ]:
# 1. Вхідні дані: два фактори та цільова змінна
x = np.array([
    [10., 2.],
    [12., 3.],
    [15., 4.],
    [18., 5.],
    [20., 6.]
])

y = np.array([21., 25., 31., 36., 40.])

# 2. Фільтрація
mask = np.isfinite(x).all(axis=1) & np.isfinite(y)
x = x[mask]
y = y[mask]

# 3. Стандартизація ознак
mu = x.mean(axis=0)
sigma = x.std(axis=0)
x_std = (x - mu) / sigma

# 4. Додаємо стовпець одиниць для вільного члена
x_design = np.column_stack([
    np.ones(x_std.shape[0]),
    x_std
])

# 5. Оцінювання параметрів методом найменших квадратів
beta, *_ = np.linalg.lstsq(x_design, y, rcond=None)

# 6. Прогноз і MSE
y_pred = x_design @ beta
mse = np.mean((y - y_pred) ** 2)

print("beta =", beta)
print("y_pred =", y_pred)
print("MSE =", mse)

beta = [30.6         5.53172667  1.41421356]
y_pred = [21.1 25.1 30.6 36.1 40.1]
MSE = 0.03999999999999986


In [ ]:
# 1.
np.random.seed(42)
X = np.random.randn(5, 4)

print("1. Матриця X:")
print(X)
print("Форма:", X.shape)


# 2.
mean = X.mean(axis=0)
std = X.std(axis=0)

print("\n2. Середнє кожної ознаки:")
print(mean)

print("Стандартне відхилення кожної ознаки:")
print(std)


# 3.
X_std = (X - mean) / std

print("\n3. Стандартизована матриця:")
print(X_std)


# 4.
positive_rows = X_std[X_std[:, 0] > 0]

print("\n4. Рядки, де перша ознака додатна:")
print(positive_rows)


# 5.
X_new = np.hstack((X_std, np.ones((X_std.shape[0], 1))))

print("\n5. Матриця з новим стовпцем одиниць:")
print(X_new)


# 6.
w = np.array([0.5, -0.3, 0.2, 0.7, 1.0])

y_pred = X_new @ w

print("\n6. Вектор ваг:")
print(w)

print("Прогноз X @ w:")
print(y_pred)


# 7.
y_true = np.array([1.0, 0.5, -0.5, 1.5, 0.0])

mse = np.mean((y_true - y_pred) ** 2)

print("\n7. y_true:")
print(y_true)

print("MSE:", mse)


# 8.
print("\n8. Перевірка масивів:")

print("Чи є NaN у X:", np.isnan(X).any())
print("Чи є inf у X:", np.isinf(X).any())

print("Чи є NaN у X_std:", np.isnan(X_std).any())
print("Чи є inf у X_std:", np.isinf(X_std).any())

print("Чи є NaN у прогнозі:", np.isnan(y_pred).any())
print("Чи є inf у прогнозі:", np.isinf(y_pred).any())

1. Матриця X:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]
Форма: (5, 4)

2. Середнє кожної ознаки:
[-0.19555649 -0.28577483 -0.17389165 -0.02997128]
Стандартне відхилення кожної ознаки:
[0.53199997 0.86248072 1.16420164 1.0422819 ]

3. Стандартизована матриця:
[[ 1.30126067  0.17103052  0.70570266  1.49000106]
 [-0.07255054  0.05987133  1.50584264  0.7650579 ]
 [-0.51488329  0.96040972 -0.24869063 -0.4180812 ]
 [ 0.82240373 -1.88700499 -1.33226594 -0.51072195]
 [-1.53623058  0.69569342 -0.63058873 -1.3262558 ]]

4. Рядки, де перша ознака додатна:
[[ 1.30126067  0.17103052  0.70570266  1.49000106]
 [ 0.82240373 -1.88700499 -1.33226594 -0.51072195]]

5. Матриця з новим стовпцем одиниць:
[[ 1.30126067  0.17103052  0.70570266  1.49000106  1.        ]
 [-0.07255054  0.05987133  1.50